import type { Contact } from '../types'

export const CONTACTS: Contact[] = [
  { id: 'c-001', firstName: 'Michael', lastName: 'Torres', email: 'mtorres@gmail.com', phone: '(604) 555-1001', leadSource: 'BoldTrail IDX', tags: ['buyer', 'first-time-buyer', 'active-now'], crmId: 'bt-10001', createdAt: '2024-01-08' },
  { id: 'c-002', firstName: 'Jennifer', lastName: 'Park', email: 'jpark@outlook.com', phone: '(604) 555-1002', leadSource: 'Zillow', tags: ['seller', 'upsizing', '6-months'], crmId: 'bt-10002', createdAt: '2024-01-15' },
  { id: 'c-003', firstName: 'Robert', lastName: 'Williams', email: 'rwilliams@hotmail.com', phone: '(604) 555-1003', leadSource: 'Referral', tags: ['buyer', 'relocation', 'active-now'], crmId: 'bt-10003', createdAt: '2024-01-22' },
  { id: 'c-004', firstName: 'Amanda', lastName: 'Foster', email: 'afoster@gmail.com', phone: '(604) 555-1004', leadSource: 'Open House', tags: ['buyer', 'downsizing', '12-months'], crmId: 'bt-10004', createdAt: '2024-02-01' },
  { id: 'c-005', firstName: 'Kevin', lastName: 'Lee', email: 'klee@icloud.com', phone: '(604) 555-1005', leadSource: 'Sphere', tags: ['seller', 'investor', 'active-now'], crmId: 'bt-10005', createdAt: '2024-02-05' },
  { id: 'c-006', firstName: 'Stephanie', lastName: 'Martinez', email: 'smartinez@gmail.com', phone: '(604) 555-1006', leadSource: 'Realtor.com', tags: ['buyer', 'first-time-buyer', 'active-now'], crmId: 'bt-10006', createdAt: '2024-02-12' },
  { id: 'c-007', firstName: 'David', lastName: 'Johnson', email: 'djohnson@yahoo.com', phone: '(604) 555-1007', leadSource: 'Social Media', tags: ['seller', 'relocation'], crmId: 'bt-10007', createdAt: '2024-02-18' },
  { id: 'c-008', firstName: 'Rachel', lastName: 'Brown', email: 'rbrown@gmail.com', phone: '(604) 555-1008', leadSource: 'BoldTrail IDX', tags: ['buyer', 'investor', '6-months'], crmId: 'bt-10008', createdAt: '2024-02-25' },
  { id: 'c-009', firstName: 'Christopher', lastName: 'Davis', email: 'cdavis@gmail.com', phone: '(604) 555-1009', leadSource: 'Direct Mail', tags: ['seller', 'downsizing'], crmId: 'bt-10009', createdAt: '2024-03-01' },
  { id: 'c-010', firstName: 'Lauren', lastName: 'Wilson', email: 'lwilson@outlook.com', phone: '(604) 555-1010', leadSource: 'Referral', tags: ['buyer', 'active-now'], crmId: 'bt-10010', createdAt: '2024-03-05' },
  { id: 'c-011', firstName: 'Brandon', lastName: 'Anderson', email: 'banderson@gmail.com', phone: '(604) 555-1011', leadSource: 'Sign Call', tags: ['buyer', 'first-time-buyer'], crmId: 'bt-10011', createdAt: '2024-03-10' },
  { id: 'c-012', firstName: 'Ashley', lastName: 'Taylor', email: 'ataylor@icloud.com', phone: '(604) 555-1012', leadSource: 'Past Client', tags: ['seller', 'upsizing', 'active-now'], crmId: 'bt-10012', createdAt: '2024-03-15' },
  { id: 'c-013', firstName: 'Nathan', lastName: 'Moore', email: 'nmoore@gmail.com', phone: '(604) 555-1013', leadSource: 'Zillow', tags: ['buyer', 'relocation', 'active-now'], crmId: 'bt-10013', createdAt: '2024-03-20' },
  { id: 'c-014', firstName: 'Megan', lastName: 'Jackson', email: 'mjackson@yahoo.com', phone: '(604) 555-1014', leadSource: 'Open House', tags: ['buyer', 'just-looking'], crmId: 'bt-10014', createdAt: '2024-03-25' },
  { id: 'c-015', firstName: 'Eric', lastName: 'White', email: 'ewhite@gmail.com', phone: '(604) 555-1015', leadSource: 'BoldTrail IDX', tags: ['buyer', 'investor', 'active-now'], crmId: 'bt-10015', createdAt: '2024-04-01' },
  { id: 'c-016', firstName: 'Brittany', lastName: 'Harris', email: 'bharris@gmail.com', phone: '(604) 555-1016', leadSource: 'Agent Referral', tags: ['seller', 'downsizing', 'active-now'], crmId: 'bt-10016', createdAt: '2024-04-05' },
  { id: 'c-017', firstName: 'Andrew', lastName: 'Clark', email: 'aclark@outlook.com', phone: '(604) 555-1017', leadSource: 'Cold Call', tags: ['buyer', '12-months'], crmId: 'bt-10017', createdAt: '2024-04-10' },
  { id: 'c-018', firstName: 'Samantha', lastName: 'Lewis', email: 'slewis@gmail.com', phone: '(604) 555-1018', leadSource: 'Sphere', tags: ['seller', 'upsizing'], crmId: 'bt-10018', createdAt: '2024-04-15' },
  { id: 'c-019', firstName: 'Tyler', lastName: 'Robinson', email: 'trobinson@icloud.com', phone: '(604) 555-1019', leadSource: 'Social Media', tags: ['buyer', 'active-now'], crmId: 'bt-10019', createdAt: '2024-04-20' },
  { id: 'c-020', firstName: 'Jessica', lastName: 'Walker', email: 'jwalker@gmail.com', phone: '(604) 555-1020', leadSource: 'Realtor.com', tags: ['buyer', 'first-time-buyer', '6-months'], crmId: 'bt-10020', createdAt: '2024-04-25' },
  { id: 'c-021', firstName: 'Daniel', lastName: 'Hall', email: 'dhall@yahoo.com', phone: '(604) 555-1021', leadSource: 'BoldTrail IDX', tags: ['buyer', 'active-now'], crmId: 'bt-10021', createdAt: '2024-05-01' },
  { id: 'c-022', firstName: 'Emily', lastName: 'Allen', email: 'eallen@gmail.com', phone: '(604) 555-1022', leadSource: 'Referral', tags: ['seller', 'relocation', 'active-now'], crmId: 'bt-10022', createdAt: '2024-05-05' },
  { id: 'c-023', firstName: 'Josh', lastName: 'Young', email: 'jyoung@gmail.com', phone: '(604) 555-1023', leadSource: 'Open House', tags: ['buyer', 'just-looking'], crmId: 'bt-10023', createdAt: '2024-05-10' },
  { id: 'c-024', firstName: 'Nicole', lastName: 'King', email: 'nking@outlook.com', phone: '(604) 555-1024', leadSource: 'Past Client', tags: ['seller', 'investor', 'active-now'], crmId: 'bt-10024', createdAt: '2024-05-15' },
  { id: 'c-025', firstName: 'Patrick', lastName: 'Scott', email: 'pscott@gmail.com', phone: '(604) 555-1025', leadSource: 'Direct Mail', tags: ['buyer', '6-months'], crmId: 'bt-10025', createdAt: '2024-05-20' },
  { id: 'c-026', firstName: 'Heather', lastName: 'Green', email: 'hgreen@icloud.com', phone: '(604) 555-1026', leadSource: 'Sign Call', tags: ['buyer', 'first-time-buyer', 'active-now'], crmId: 'bt-10026', createdAt: '2024-06-01' },
  { id: 'c-027', firstName: 'Jason', lastName: 'Baker', email: 'jbaker@gmail.com', phone: '(604) 555-1027', leadSource: 'Zillow', tags: ['buyer', 'investor'], crmId: 'bt-10027', createdAt: '2024-06-05' },
  { id: 'c-028', firstName: 'Rebecca', lastName: 'Adams', email: 'radams@yahoo.com', phone: '(604) 555-1028', leadSource: 'BoldTrail IDX', tags: ['buyer', 'relocation', 'active-now'], crmId: 'bt-10028', createdAt: '2024-06-10' },
  { id: 'c-029', firstName: 'Austin', lastName: 'Nelson', email: 'anelson@gmail.com', phone: '(604) 555-1029', leadSource: 'Agent Referral', tags: ['seller', 'upsizing', 'active-now'], crmId: 'bt-10029', createdAt: '2024-06-15' },
  { id: 'c-030', firstName: 'Kayla', lastName: 'Carter', email: 'kcarter@outlook.com', phone: '(604) 555-1030', leadSource: 'Sphere', tags: ['buyer', 'downsizing', '12-months'], crmId: 'bt-10030', createdAt: '2024-06-20' },
  { id: 'c-031', firstName: 'Sean', lastName: 'Mitchell', email: 'smitchell@gmail.com', leadSource: 'Cold Call', tags: ['buyer'], createdAt: '2024-07-01' },
  { id: 'c-032', firstName: 'Tiffany', lastName: 'Perez', email: 'tperez@gmail.com', leadSource: 'Social Media', tags: ['seller', 'active-now'], createdAt: '2024-07-05' },
  { id: 'c-033', firstName: 'Corey', lastName: 'Roberts', email: 'croberts@icloud.com', leadSource: 'Realtor.com', tags: ['buyer', 'active-now'], createdAt: '2024-07-10' },
  { id: 'c-034', firstName: 'Vanessa', lastName: 'Turner', email: 'vturner@gmail.com', leadSource: 'Open House', tags: ['buyer', 'first-time-buyer'], createdAt: '2024-07-15' },
  { id: 'c-035', firstName: 'Marcus', lastName: 'Phillips', email: 'mphillips@yahoo.com', leadSource: 'BoldTrail IDX', tags: ['buyer', 'investor', 'active-now'], createdAt: '2024-07-20' },
  { id: 'c-036', firstName: 'Courtney', lastName: 'Campbell', email: 'ccampbell@gmail.com', leadSource: 'Referral', tags: ['seller', 'relocation'], createdAt: '2024-08-01' },
  { id: 'c-037', firstName: 'Derek', lastName: 'Parker', email: 'dparker@outlook.com', leadSource: 'Past Client', tags: ['buyer', 'upsizing', 'active-now'], createdAt: '2024-08-05' },
  { id: 'c-038', firstName: 'Monica', lastName: 'Evans', email: 'mevans@gmail.com', leadSource: 'Sign Call', tags: ['buyer'], createdAt: '2024-08-10' },
  { id: 'c-039', firstName: 'Ian', lastName: 'Edwards', email: 'iedwards@icloud.com', leadSource: 'Direct Mail', tags: ['seller', 'downsizing'], createdAt: '2024-08-15' },
  { id: 'c-040', firstName: 'Crystal', lastName: 'Collins', email: 'ccollins@gmail.com', leadSource: 'BoldTrail IDX', tags: ['buyer', 'active-now'], createdAt: '2024-09-01' },
  { id: 'c-041', firstName: 'Dustin', lastName: 'Stewart', email: 'dstewart@yahoo.com', leadSource: 'Zillow', tags: ['buyer', 'first-time-buyer', 'active-now'], createdAt: '2024-09-10' },
  { id: 'c-042', firstName: 'Felicia', lastName: 'Sanchez', email: 'fsanchez@gmail.com', leadSource: 'Agent Referral', tags: ['seller', 'investor', 'active-now'], createdAt: '2024-09-15' },
  { id: 'c-043', firstName: 'Greg', lastName: 'Morris', email: 'gmorris@gmail.com', leadSource: 'Social Media', tags: ['buyer', 'relocation'], createdAt: '2024-09-20' },
  { id: 'c-044', firstName: 'Haley', lastName: 'Rogers', email: 'hrogers@outlook.com', leadSource: 'Open House', tags: ['buyer', 'just-looking'], createdAt: '2024-10-01' },
  { id: 'c-045', firstName: 'Ivan', lastName: 'Reed', email: 'ireed@gmail.com', leadSource: 'Sphere', tags: ['seller', 'active-now'], createdAt: '2024-10-05' },
  { id: 'c-046', firstName: 'Julia', lastName: 'Cook', email: 'jcook@icloud.com', leadSource: 'Referral', tags: ['buyer', 'upsizing', 'active-now'], createdAt: '2024-10-10' },
  { id: 'c-047', firstName: 'Karl', lastName: 'Morgan', email: 'kmorgan@gmail.com', leadSource: 'BoldTrail IDX', tags: ['buyer', 'active-now'], createdAt: '2024-10-15' },
  { id: 'c-048', firstName: 'Lisa', lastName: 'Bell', email: 'lbell@yahoo.com', leadSource: 'Past Client', tags: ['seller', 'downsizing', 'active-now'], createdAt: '2024-10-20' },
  { id: 'c-049', firstName: 'Matt', lastName: 'Murphy', email: 'mmurphy@gmail.com', leadSource: 'Cold Call', tags: ['buyer'], createdAt: '2024-11-01' },
  { id: 'c-050', firstName: 'Nina', lastName: 'Rivera', email: 'nrivera@outlook.com', leadSource: 'Realtor.com', tags: ['buyer', 'first-time-buyer', 'active-now'], createdAt: '2024-11-05' },
  { id: 'c-051', firstName: 'Oscar', lastName: 'Price', email: 'oprice@gmail.com', leadSource: 'BoldTrail IDX', tags: ['buyer', 'investor'], createdAt: '2024-11-10' },
  { id: 'c-052', firstName: 'Paula', lastName: 'Bailey', email: 'pbailey@gmail.com', leadSource: 'Sign Call', tags: ['buyer', 'active-now'], createdAt: '2024-11-15' },
  { id: 'c-053', firstName: 'Quinn', lastName: 'Gonzalez', email: 'qgonzalez@icloud.com', leadSource: 'Direct Mail', tags: ['seller', 'relocation', 'active-now'], createdAt: '2024-12-01' },
  { id: 'c-054', firstName: 'Randy', lastName: 'Hughes', email: 'rhughes@gmail.com', leadSource: 'Zillow', tags: ['buyer', 'active-now'], createdAt: '2025-01-05' },
  { id: 'c-055', firstName: 'Susan', lastName: 'Flores', email: 'sflores@yahoo.com', leadSource: 'Agent Referral', tags: ['seller', 'upsizing', 'active-now'], createdAt: '2025-01-10' },
]

export const CONTACT_BY_ID = Object.fromEntries(
  CONTACTS.map((c) => [c.id, c])
) as Record<string, Contact>
